-x, --trace <level>

diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -109,11 +109,13 @@ bats_exit_trap() {
     bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
     bats_print_failed_command >&3
 
-    while IFS= read -r line; do
-      printf '# %s\n' "$line" || break # avoid feedback loop when errors are redirected into BATS_OUT (see #353)
-    done <"$BATS_OUT" >&3
-    if [[ -n "$line" ]]; then
-      printf '# %s\n' "$line"
+    if [[ "${TRACE_LEVEL}" -le 1 ]]; then
+      while IFS= read -r line; do
+        printf '# %s\n' "$line" || break # avoid feedback loop when errors are redirected into BATS_OUT (see #353)
+      done <"$BATS_OUT" >&3
+      if [[ -n "$line" ]]; then
+        printf '# %s\n' "$line"
+      fi
     fi
     status=1
   else
