LEVEL 2 output on failure + other fixes

diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -105,20 +105,33 @@ bats_exit_trap() {
       BATS_STACK_TRACE=("${BATS_CURRENT_STACK_TRACE[@]}")
       BATS_ERROR_STATUS=1
     fi
+    if [[ -z "${TRACE_LEVEL}" || "${TRACE_LEVEL}" -gt 0 ]]; then
+      if [[ -n "$BATS_TRACE_COMMAND" ]]; then
+        printf "# COMMAND: %s\n" "${BATS_TRACE_COMMAND}" >&3
+        if [[ -n "${BATS_TRACE_COMMAND_OUTPUT}" ]]; then
+          printf "#   %s\n" "${BATS_TRACE_COMMAND_OUTPUT[@]}" >&3
+        fi
+      fi
+    fi
     printf 'not ok %d %s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" >&3
     bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
     bats_print_failed_command >&3
 
-    if [[ "${TRACE_LEVEL}" -le 1 ]]; then
-      while IFS= read -r line; do
-        printf '# %s\n' "$line" || break # avoid feedback loop when errors are redirected into BATS_OUT (see #353)
-      done <"$BATS_OUT" >&3
-      if [[ -n "$line" ]]; then
-        printf '# %s\n' "$line"
-      fi
+    while IFS= read -r line; do
+      printf '# %s\n' "$line" || break # avoid feedback loop when errors are redirected into BATS_OUT (see #353)
+    done <"$BATS_OUT" >&3
+    if [[ -n "$line" ]]; then
+      printf '# %s\n' "$line"
     fi
+
     status=1
   else
+    if [[ "${TRACE_LEVEL}" -gt 0 && -n "$BATS_TRACE_COMMAND" ]]; then
+      printf "  COMMAND: %s\n" "${BATS_TRACE_COMMAND}" >&3
+      if [[ "${TRACE_LEVEL}" -gt 1 && -n "${BATS_TRACE_COMMAND_OUTPUT}" ]]; then
+        printf "    %s\n" "${BATS_TRACE_COMMAND_OUTPUT[@]}" >&3
+      fi
+    fi
     printf 'ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" \
       "$skipped" >&3
     status=0
